#ifndef GAMESTATE_H
#define GAMESTATE_H

namespace model {

enum GameState{
    INSCRIPTIONPLAYER1=0,INSCRIPTIONPLAYER2=1,CONFIGPLAYER1=2,CONFIGPLAYER2=3,INPROCESS=4,INFIGHT=5,END=6
};

}


#endif // GAMESTATE_H
